# Generated by Django 3.0.8 on 2020-07-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('date', models.CharField(max_length=20)),
            ],
        ),
    ]
