# Generated by Django 3.0.8 on 2020-08-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_auto_20200801_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='race',
            name='flag_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
