# Generated by Django 3.0.8 on 2020-08-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_auto_20200801_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='location',
            field=models.CharField(default=2, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='race',
            name='date',
            field=models.CharField(max_length=21),
        ),
    ]
