# Generated by Django 3.0.8 on 2020-08-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_auto_20200803_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='race_views',
            field=models.IntegerField(default=0),
        ),
    ]
