# Generated by Django 3.0.8 on 2020-11-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(default=1, editable=False, max_length=16),
            preserve_default=False,
        ),
    ]
