# Generated by Django 3.0.8 on 2020-12-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20201107_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
